### PR TITLE
Add initial providers - Review before merging 

### PR DESCRIPTION
**Pull request by ulut0002**
Hi @sous0049 ,

I added the basic providers for the code. AuthProvider, UIProvider and AppProvider. 

- AppProvider: Holds all app specific code (e.g. health check)
- UIProvider: State variable for whether the menu is open or closed in mobile version
- AuthProvider: Provides the fact that whether the user is logged in or not. 

If you check the code, you'll see there is a bunch of warnings for naming conventions in app/providers.js  it says _"providers.js does not match filename pattern.eslint[validate-filename/naming-rules](file:///)"_. It is understandable based on 
[this format](https://vercel.com/guides/react-context-state-management-nextjs):  My only option is to add providers.js into Components folder as a component. 

Please review. Thanks

### CODE REVIEW

**Comment by ulut0002** [comment]
I also selected "main" by mistake. Do not merge under any circumstances.

**Comment by sous0049** [comment]
Good morning Serdar!

Please review the naming convention as follow. 
image

**Comment by sous0049** [comment]
The Validation on Vercel and Netlify failed, fix before merging.

**Comment by sous0049** [comment]
Files must be .jsx not js.

**Review by sous0049 — CHANGES_REQUESTED** [review]
Fix file naming, and change the pull to dev branch.

**Comment by sous0049** [comment]
Also the providers import on app.jsx is missing the file extension.

**Comment by ulut0002** [comment]
@sous0049 

I added the "providers" file name to eslinttrc.json document. This was the main issue. But I also changed the file extensions from js to jsx under providers folder. Thanks!

**Comment by ulut0002** [comment]
I was able to change it from main to dev. It is good for review and merge now.

**Comment by sous0049** [comment]
You should not edit the eslinttrc.json as that was set to fit the patterns created in the code guidelines. App folder should be used for routing purposes as stated in the coding guidelines. I will approved, but please follow coding guidelines.

**Comment by ulut0002** [comment]
In that case, you won't be able to add "providers.jsx" under the app folder. It has to go as a component under components folder. 

https://vercel.com/guides/react-context-state-management-nextjs : providers.js is under app folder here.

**Comment by sous0049** [comment]
If you check the files on the website that you provided, everything is being stored in the /app folder in that case we should adapt examples to our scenario, not blatantly copy.

**Pull request merged**
